name: BackFrameX
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libffi=3.4.4
  - libmpdec=4.0.0
  - openssl=3.0.16
  - pip=25.1
  - python=3.13.2
  - python_abi=3.13
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - aiosmtplib==3.0.2
      - aiosqlite==0.21.0
      - alembic==1.15.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - bcrypt==3.2.2
      - blinker==1.9.0
      - certifi==2025.4.26
      - cffi==1.17.1
      - click==8.1.8
      - colorama==0.4.6
      - dnspython==2.7.0
      - email-validator==2.2.0
      - fastapi==0.115.12
      - fastapi-cli==0.0.7
      - fastapi-mail==1.4.2
      - greenlet==3.2.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - mako==1.3.10
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - passlib==1.7.4
      - pycparser==2.22
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydantic-settings==2.9.1
      - pygments==2.19.1
      - pyjwt==2.10.1
      - python-dotenv==1.1.0
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - rich==14.0.0
      - rich-toolkit==0.14.6
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sqlalchemy==2.0.41
      - starlette==0.46.2
      - typer==0.15.4
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - uvicorn==0.34.2
      - watchfiles==1.0.5
      - websockets==15.0.1
