site_name: Documentación | MolGC Web App
site_description: Molecular Geometry Comparator Algorithm for Bond Length Mean Absolute Error Computation on Molecules
site_author: Abimael Guzman | Javier Camarillo | Angel Fernandez
site_url: https://molgc.eonia.io/docs/

docs_dir: src/docs

extra:
  base_url: /docs/

extra_css:
  - assets/css/styling.css

theme:
  name: material
  custom_dir: src/overrides
  logo: assets/images/logotipo_bw.png
  favicon: assets/images/favicon.ico
  language: es

nav:
  - Inicio: index.md
  - Guía de usuario:
      - Inicio: users/index.md
  - Documentación técnica:
      - Inicio: developers/index.md
      - Instalación: developers/installation.md
      - Backend: developers/backend.md
      - Frontend: developers/frontend.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - def_list
  - attr_list

plugins:
  - search
  # - mkdocstrings
  # - git-revision-date