name: CI & Deploy for Frontend

on:
  push:
    branches:
      - feature/frontend

env:
  REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  IMAGE_NAME_FRONTEND: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}_frontend

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.PAT }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}:latest

  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Copy docker-compose file
        run: |
          scp docker-compose.frontend.yml \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/docker-compose.frontend.yml
        shell: bash

      - name: Deploy on remote
        run: |
          ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.WORK_DIR }}

            export REGISTRY=${{ env.REGISTRY }}
            export IMAGE_NAME_FRONTEND=${{ env.IMAGE_NAME_FRONTEND }}
            export APP_NAME=${{ secrets.APP_NAME }}

            ENV_FRONTEND='${{ secrets.ENV_FRONTEND }}'

            ENV_CONTENT="${ENV_FRONTEND}"
            printf "%s\n" "$ENV_CONTENT" > /tmp/deploy.env

            docker compose \
              --env-file /tmp/deploy.env \
              -f docker-compose.frontend.yml pull

            docker compose \
              --env-file /tmp/deploy.env \
              -f docker-compose.frontend.yml up -d --remove-orphans

            rm /tmp/deploy.env
          EOF
        shell: bash